# Generated by Django 3.2.8 on 2022-05-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trench', '0003_auto_20190213_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfamethod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
