# Generated by Django 3.2.8 on 2022-05-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trench', '0004_alter_mfamethod_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfamethod',
            name='ip_whitelist',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mfamethod',
            name='remember',
            field=models.DateField(blank=True, null=True),
        ),
    ]
